---
title: "Arboles"
author: "Ricardo Zamora Mennigke"
date: "3/19/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


##Arboles de decision
```{r eval=TRUE, results='hide', message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(dplyr)
library(glue)
library(scales)
library(rpart)
library(rpart.plot)
```

```{r}
setwd("C:/Users/rzamoram/OneDrive - Intel Corporation/Documents/ULACIT/Probabilidades")
datos<-read.csv("voces.csv")
str(datos)
```
#Matriz confusion
```{r}
indices.general <- function(MC){
  precision.global <- sum(diag(MC))/sum(MC)
  error.global <- 1 - precision.global
  precision.categoria <- diag(MC)/rowSums(MC)
  precision.positiva <- MC[2, 2]/(MC[2, 2] + MC[2, 1])
  precision.negativa <- MC[1, 1]/(MC[1, 1] + MC[1, 2])
  falsos.positivos <- 1 - precision.negativa
  falsos.negativos <- 1 - precision.positiva
  asertividad.positiva <- MC[2, 2]/(MC[1, 2] + MC[2, 2])
  asertividad.negativa <- MC[1, 1]/(MC[1, 1] + MC[2, 1])
  res <- list(matriz.confusion = MC, precision.global = precision.global, error.global = error.global, 
              precision.categoria = precision.categoria, precision.positiva = precision.positiva, precision.negativa=precision.negativa, 
              falsos.positivos=falsos.positivos, falsos.negativos=falsos.negativos, asertividad.positiva=asertividad.positiva,
              asertividad.negativa=asertividad.negativa)
  names(res) <- c("Matriz de Confusión", "Precisión Global", "Error Global", "Precisión por categoría", "Precision Positiva", "Precision Negativa",
                  "Falsos Positivos", "Falsos Negativos", "Asertividad Positiva", "Asertividad Negativa")
  return(res)
}
```

```{r}
muestra <- sample(1:nrow(datos), floor(nrow(datos)*0.20))
ttesting <- datos[muestra,]
taprendizaje <-datos[-muestra,]
modelo<-rpart(genero~.,data=taprendizaje)
prediccion <-predict(modelo, ttesting, type='class')
prp(modelo, extra=106, branch.type=2, box.col = c("pink", "palegreen3", "cyan")[modelo$frame$yval])
```

